### ISSUE TITLE
Honor custom labels on ingress definition

### ISSUE THREAD

**Issue by twe-syde** [PrivateBin/helm-chart#100]
In order to get for example HTTP-01 challenge working custom labels should be honored by the ingress template.

values.yaml

```
ingress:
  enabled: true
  className: external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    use-http01-solver: "true" <----
```

templates/ingress.yaml

```
...
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "privatebin.name" . }}
    helm.sh/chart: {{ include "privatebin.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.ingress.labels }} <----
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
...
```
