### ISSUE TITLE
Security considerations about Pod user

### ISSUE THREAD

**Issue by gillg** [PrivateBin/helm-chart#31]
Hi,

When you enforce a "good" PSP to deny launch root pods you can't launch privatebin pod.
In fact, container runs as a random non root user (called "nobody" and created in dockerfile), but kubernetes can't determine its UID to check if is different of 0.

`Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root`

I made a little test like this :
```yaml
    spec:
      securityContext:
        runAsUser: 65534
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
```

It works perfectly because 65534 is the UID of "nobody" user, but it seems not a stable solution because UID is not guaranteed.
Anyone has any idea to make it clean ?
Or we just should make a change in dockerfile to fix an ID ? https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L54
