### ISSUE TITLE
serviceName needs to be added to templates/statefulset.yaml

### ISSUE THREAD

**Issue by travnewmatic** [PrivateBin/helm-chart#33]
Please see:

- https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
- https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/

At some point, spec.serviceName became required for StatefulSet resources.  

Currently, the helm chart will not install if the value service.controller.kind is set to StatefulSet, because there is no spec.serviceName in templates/statefulset.yaml.

Please consider adding something like the following to templates/statefulset.yaml:
```    
     app.kubernetes.io/instance: {{ .Release.Name }}
     app.kubernetes.io/managed-by: {{ .Release.Service }}
 spec:
+  serviceName: {{ include "privatebin.name" . }}                                                  
   selector:
     matchLabels:
       app.kubernetes.io/name: {{ include "privatebin.name" . }}
```

Thanks for all the hard work on such an awesome project!
