### ISSUE TITLE
Share PVC between pods in HA setup 

### ISSUE THREAD

**Issue by hbollon** [PrivateBin/helm-chart#89]
Hello,

I'm currently planning to evolve our PrivateBin instance to have multiples replicas.
I currently use it with a Statefulset and a PVC, however, I noticed that if I add a replica it will create his own PVC which cause issues to open URLs generated with the pod A on the pod B and vice versa.
Does it exist a trick with this chart to solve this behavior? If no, can it be an interesting feature to add?

Thanks in advance !

**Comment by janosmiko** [comment]
I've created a dedicated PVC in RWX mode using longhorn and mounted that PVC for the deployments.

pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-pvc
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
```

values.yaml
```
replicaCount: 2
controller:
  kind: Deployment

extraVolumes:
  - name: privatebin-pvc
    persistentVolumeClaim:
      claimName: privatebin-pvc

extraVolumeMounts:
  - name: privatebin-pvc
    mountPath: /srv/data

```
