### ISSUE TITLE
config is not being applied after deployment via argocd

### ISSUE THREAD

**Issue by licentiapoetica** [PrivateBin/helm-chart#93]
Hello, as the title already says:

The conf.php is not being applied when I try to deploy it to my cluster, however it does deploy without any problems or issues, but the conf.php is just being ignored in the final deployment.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin
  namespace: argocd
spec:
  project: test-privatebin
  source:
    chart: privatebin
    repoURL: https://privatebin.github.io/helm-chart/
    targetRevision: 0.21.0
    helm:
      releaseName: test-privatebin
      valuesObject:
        config:          
          conf.php: |-
            [main]      
            name = "Testbin"
            fileupload = false
            discussion = false
            password = true
            burnafterreadingselected = true
            template = "bootstrap"
            notice = "Pastebin Test Deployment"
            languageselection = true
            languagedefault = "en"
            [expire]
            default = "1day"
            [model]
            class = Filesystem
            [model_options]
            dir = PATH "data"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: testprivatebin
```

When I describe the configmap  in the cluster I get the following

```
│ Annotations:  <none>                                                                                                                                                                                                                     │
│                                                                                                                                                                                                                                          │
│ Data                                                                                                                                                                                                                                     │
│ ====                                                                                                                                                                                                                                     │
│                                                                                                                                                                                                                                          │
│ BinaryData                                                                                                                                                                                                                               │
│ ====                                                                                                                                                                                                                                     │
│                                                                                                                                                                                                                                          
```

I also entered the pod via shell to see if the config somehow shows up but it nowhere to be found.

At this point I do not know where to look or what may cause this, if someone has an idea please let me know!
